version: "3"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: qover
      POSTGRES_USER: qover
      POSTGRES_DB: qover-local
